Peacher/Peacher/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ideapeacher.urls')),
    path('',include('sponser.urls')),
]

urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Peacher/ideapeacher/urls.py
from django.urls import path
from . import views

app_name='ideapeacher'

urlpatterns = [
    path('registerPeacher/',views.register_user, name='register_form'),
    path('loginPeacher/',views.login_user,name='login_form'),
    path('logoutPeacher/',views.logout_user,name='logout_form'),
    path('home/',views.ideapeacherpage,name='home'),
    path('homesponser/',views.sponserPage,name='home_sponser'),
    path('submitIdeas/',views.submitIdea, name='submitidea'),
    path('idea/',views.post, name='idea'),
    path('comment/<int:pk>/',views.comment, name='comment'),
    path('edit_idea/<int:pk>/',views.edit_idea, name='edit_idea'),
    path('updateidea/<int:pk>/',views.updateidea, name='updateidea'),
    path('delete/<int:pk>/',views.delete, name='delete'),
]

Peacher/ideapeacher/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

# Create your models here.



class MyUser(models.Model):
    user = models.OneToOneField(User, null= True, on_delete= models.CASCADE)
    name = models.CharField(max_length=200, null= True)
    idprove = models.CharField(max_length=50, null=True)
    idproveno = models.CharField(max_length=30, null=True)
    mobile = models.CharField(max_length=10, null=True)

    def __str__(self):
        return self.name

class category(models.Model):
    category = models.CharField(max_length=100)

class idea(models.Model):
    peacher = models.ForeignKey(MyUser, on_delete=models.CASCADE,default=False)
    Post_idea = models.TextField()
    date_created = models.DateTimeField(default = datetime.now())
    pdf = models.FileField(upload_to="book/pdfs",blank=True)
    category =models.ManyToManyField(category)

    def __str__(self):
        return self.Post_idea


class Public(models.Model):
    comment = models.TextField()
    date_created = models.DateTimeField(default=datetime.now())
    on_post = models.ForeignKey(idea, on_delete=models.CASCADE, default=None)
    byUser = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.comment

Peacher/ideapeacher/forms.py
from django.forms import ModelForm, fields
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth.models import User
from .models import MyUser
from django import forms


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = {'username','email','password1','password2'}

Peacher/ideapeacher/views.py
from datetime import datetime
from  ideapeacher.decorators import ideapeacher_only,allowed_users
from django.core.checks import messages
from django.shortcuts import redirect, render
from .forms import CreateUserForm
from .models import MyUser, Public, category, idea
from django.contrib import messages
from django.http import HttpResponse
from django.contrib.auth.models import Group

from django.contrib.auth import authenticate,login,logout
# Create your views here.

def register_user(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
        
        if not Group.objects.filter(name='ideapeacher').exists():
            group = Group.objects.create(name='ideapeacher')
            addtogroup = Group.objects.get(name='ideapeacher')
            user.groups.add(addtogroup)

            MyUser.objects.create(user=user,name=user.username)
            messages.success(request, "Account was Created for "+ username)
            return HttpResponse("Created user with group Ideapeacher")
        
        else:
            group = Group.objects.get(name='ideapeacher')
            user.groups.add(group)

            MyUser.objects.create(user=user , name=user.username)
            messages.success(request, "Account was Created for "+ username)
            return HttpResponse("Created user with group Ideapeacher")
    
    context ={'form':form}

    return render(request,'main/register.html',context)


def login_user(request):
    if request.method == 'POST':
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(request,username=username,password=password)

        if user is not None:
            login(request,user)
            return HttpResponse("Login Successful")

        else:
            messages.info(request,'username or password is wrong')

    return render(request,"main/login.html")

def logout_user(request):
    logout(request)
    return redirect('ideapeacher:login_form')


@ideapeacher_only
def ideapeacherpage(request):
    ideas =idea.objects.all()
    comment = Public.objects.all()
    return render(request, "main/home.html",{'idea':ideas,'comments':comment})

@allowed_users(allowed_roles=['sponser'])
def sponserPage(request):
    users = MyUser.objects.all()
    ideas = idea.objects.all()
    comment = Public.objects.all()

    return render(request,"main/homesponser.html",{'ideas':ideas,'users':users,'comments':comment})

@allowed_users(allowed_roles=['ideapeacher'])
def submitIdea(request):
    if request.method == "POST":
        data = request.POST.get("dropdown")

        if category.objects.filter(category=data).exists():
            fdata = category(category=data)
            fdata.save()

            idea1 = request.POST.get("idea")
            user1 = MyUser.objects.get(user = request.user)
            pdf = request.FILES.get('pdf')

            date = datetime.now()

            post = idea(peacher=user1, post_idea = idea1, date_created = date, pdf=pdf)
            post.save()
            post.category.add(fdata)

            return redirect('/home')
        
        else:
            cat=category.objects.get(category=data)

            idea1 = request.POST.get("idea")
            user1 = MyUser.objects.get(user = request.user)
            pdf = request.FILES.get('pdf')

            date = datetime.now()
            post = idea(peacher=user1, post_idea = idea1, date_created = date, pdf=pdf)
            post.save()
            post.category.add(cat)
    
    return redirect("/home")


def post(request):
    return render(request,"main/addidea.html")



def comment(request,pk):
    if request.method == "POST":
        post=idea.objects.get(pk=pk)
        comm=request.POST.get("comment")
        user=request.user
        date=datetime.now()
        data = Public(comment=comm,date_created=date,on_post=post,byUser=user)
        data.save()

    return redirect("/home")

@allowed_users(allowed_roles=['ideapeacher'])
def edit_idea(request,pk):
    id=idea.objects.get(pk=pk)
    context={'edit':id}
    return render(request,"main/edit.html",context)

@allowed_users(allowed_roles=['ideapeacher'])
def updateidea(request,pk):
    ids = idea.objects.get(pk=pk)
    ids.Post_idea = request.POST.get('idea')
    ids.save()
    return redirect("/home")

@allowed_users(allowed_roles=['ideapeacher'])
def delete(request,pk):
    ids=idea.objects.get(pk=pk)
    ids.delete()
    return redirect("/home")

Peacher/ideapeacher/templates/main/addidea.html
<form method="POST" action="{% url 'ideapeacher:submitidea' %}" enctype="multipart/form-data">
    {% csrf_token %}

    <select name="dropdown">
        <option value="Technology">Technology</option>
        <option value="Business">Business</option>
        <option value="Health">Health</option>
        <option value="LifeHacks">Life Hacks</option>
    </select>

    <br>
    <br>
    <p>Idea</p>
    <textarea name="idea"></textarea>
    <input type="file" name="pdf">
    <button type="submit">Submit</button>
</form>

Peacher/ideapeacher/templates/main/edit.html
{% extends "main/header.html" %}

{% block content %}

<form method="POST" action="{% url 'ideapeacher:updateidea' edit.pk %}">
    {% csrf_token %}
    <textarea class="form-control" aria-label="with textarea" name="idea">{{edit.Post_idea}}</textarea>
    <button type="submit" id="submitbtn" class="btn">Update</button>
</form>

{% endblock %}

Peacher/ideapeacher/templates/main/header.html
<header>
     <!-- Compiled and minified CSS -->
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

     <!-- Compiled and minified JavaScript -->
     <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
             
</header>
<body>
    <!--nav bar-->
    <nav>
        <div class="nav-wrapper">
          <a href="#" class="brand-logo">Logo</a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href="{% url 'ideapeacher:login_form' %}">Login</a></li>
            <li><a href="{% url 'ideapeacher:logout_form' %}">Logout</a></li>
            <li><a href="{% url 'ideapeacher:idea' %}">Post</a></li>
          </ul>
        </div>
      </nav>

      <div class="container" id="frontend">
          {% block content %}
          {% endblock %}
      </div>
</body>

Peacher/ideapeacher/templates/main/home.html
{% if idea %}

{% for i in idea %}

<p>User :{{ i.peacher }}</p>
<p> {{i.date_created}} </p>

{% for c in i.category.all %}
    {{c.category}}

    <div>
        <a href="">Edit</a>
        <a href="">Delete</a>
    </div>
    <p>{{i.post_idea}}</p>
{% endfor %}

{% endfor %}

{% endif %}

Peacher/ideapeacher/templates/main/homesponser.html
{% extends "main/header.html" %}

{% block content %}
{% if ideas %}

{% for i in ideas %}

<p>User :{{ i.peacher }}</p>
<p> {{i.date_created}} </p>

{% for c in i.category.all %}
    {{c.category}}

    <p>{{i.Post_idea}}</p>

    <div>
        Comments:<br>
        {% for com in comments %}
        {% ifequal i.id com.on_post.id %}
        <p>{{com.byUser}}: {{com.comment}}</p>

        {% endifequal %}
        {% endfor %}
        <br>
        <form method="POST" action="{% url 'ideapeacher:comment' i.pk %}">
            {% csrf_token %}
            <textarea class="form-control" aria-label="with textarea" name="comment" placeholder="comment here"></textarea>
            <button type="submit" id="submitbtn" class="btn">Comment</button>
        </form>
    </div>
{% endfor %}

{% endfor %}

{% endif %}
{% endblock %}

Peacher/ideapeacher/templates/main/login.html
<form method="POST">
    {% csrf_token %}

    <input type="text" name="username" placeholder="Enter Username">

    <input type="password" name="password" placeholder="Enter Password">

    <button type="submit">Login</button>
</form>

Peacher/ideapeacher/templates/main/register.html
<h1>Register User</h1>
<form method="POST">
    {% csrf_token %}
     
    {{form.as_p}}

    <button type="submit">Sign Up</button>
</form>